# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcc-senai-cm
  namespace: tcc-senai
data:
  PROVEDOR: Azure

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: tcc-senai-svc
  namespace: tcc-senai
spec:
  selector:
    app: tcc-senai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-senai
  namespace: tcc-senai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-senai
  template:
    metadata:
      labels:
        app: tcc-senai
      annotations:
        dapr.io/app-id: "tccapp"
        dapr.io/app-port: "5000"
        dapr.io/config: "tcc-config"
        dapr.io/enabled: "true"
    spec:
      containers:
        - name: tcc-senai
          image: adansmashni/tcc-senai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: tcc-senai-cm
      imagePullSecrets:
        - name: dockerhub-credentials
